### ISSUE TITLE
Should Use ThinPDOWrapper

### ISSUE THREAD

**Issue by CarlQLange** [zmaril/squint#1]
https://github.com/mikehenrty/thin-pdo-wrapper

**Comment by zmaril** [comment]
Prototyping in lisp right now, will switch to php when we need to speed things up.

**Comment by CarlQLange** [comment]
That is, if @mikehenrty is still supporting thin-pdo-wrapper

**Comment by mikehenrty** [comment]
When you're ready for a **real** programming language, **PHP** will be ready.

**Comment by zmaril** [comment]
I'm not ready.
